apiVersion: apps/v1
kind: Deployment
metadata:
 name: cerdep
spec:
 selector:
   matchLabels:
     app: cerner-app
 replicas: 1
 template:
   metadata:
     labels:
       app: cerner-app
   spec:
     containers:
     - name: cerner-kube
   # enter the path to your image, be sure to include the correct region prefix
       image: iad.ocir.io/gse00014942/cerner/api:ocir
       #command: [ "/bin/sh", "-c", "--" ]
       #args: [ "while true; do sleep 30; done; npm start;" ]
       ports:
       - containerPort: 3000
     imagePullSecrets:
   # enter the name of the secret you created
     - name: ocirsecret4
---
apiVersion: v1
kind: Service
metadata:
 name: ser-cer
spec:
 type: LoadBalancer
 ports:
 - port: 80
   protocol: TCP
   targetPort: 3000
 selector:
   app: cerner-app