apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: santosh-cerneroci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: santosh-cerneroci
    spec:
      containers:
      - name: santosh-cerneroci
        image: iad.ocir.io/gse00014942/santoshtest/test-demo:latest
        #command: [ "/bin/sh", "-c", "--" ]
        #args: [ "while true; do sleep 30; done; npm start;" ]
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.25"
