apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: santosh-cerner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: santosh-cerner
    spec:
      containers:
      - name: santosh-cerner
        image: iad.ocir.io/gse00014942/santoshtest:test
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.25"
