apiVersion: v1
kind: Service
metadata:
  name: santosh-cerneroci
  labels:
    app: santosh-cerneroci
spec:
  selector:
    app: santosh-cerneroci
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30003
  type: LoadBalancer
